yarnPath: .yarn/releases/yarn-3.6.4.cjs
packageExtensions:
  'unplugin-vue-router@*':
    dependencies:
      '@vue/compiler-sfc': '*'
  '@unocss/inspector@*':
    dependencies:
      '@unocss/core': '*'
  '@vue/test-utils@*':
    dependencies:
      '@vue/compiler-dom': '*'
      '@vue/server-renderer': '*'
